// src/types/discovery.ts

// Represents the AI-generated insights from the initial discovery process
export interface DiscoveryResponse {
  current_state: {
    barrier_themes?: string[]; // Insightful themes that the AI has identified from the prospect's current situation and barriers
    emotions: string[]; // Emotions that the AI has identified from the prospect's current situation
    financial_risk?: string; // Financial risk and urgency (based on date that barriers must be removed) identified by the AI
  };
  future_state: {
    outcome_themes?: string[]; // Insightful themes that the AI has identified from the prospect's future desired outcomes
    emotions: string[]; // Emotions that the AI has identified from the prospect's future desired outcomes
    financial_impact?: string; // Potential financial impact once the barriers are removed
  };
}

// Comprehensive information about the prospect
export interface ProspectInfo {
  firstName: string; // Prospect's first name
  lastName: string; // Prospect's last name
  email: string; // Prospect's email address
  companyName: string; // Prospect's company name
  clientId?: string; // Identifier for the solution provider company
  userId?: string; // Identifier for the solution provider user
  industryType?: string; // Prospect's industry classification
  companySize?: string; // Size of the prospect's company
  urgencyLevel?: 'low' | 'medium' | 'high'; // Prospect's perceived urgency of solving their challenges
}

// Detailed solution response with rich, HTML-formatted content
export interface SolutionResponse {
  solution_description: {
    transformation_journey: {
      current_situation: string;  // HTML-formatted description of the current situation
      challenges: string;         // HTML-formatted list of existing challenges
      vision: string;             // HTML-formatted description of the desired future state
    };
    solution_recommendation: {
      overview: string;          // High-level solution overview
      key_components: string;    // Detailed components of the proposed solution
      approach: string;          // Structured approach to implementing the solution
    };
    value_proposition: {
      business_outcomes: string;  // Expected business-level results
      personal_benefits: string;  // Benefits for individual stakeholders
      risk_mitigation: string;   // Strategies to address potential risks
    };
    investment_summary: {
      pricing_model: string;     // Breakdown of solution costs
      roi_analysis: string;      // Return on investment analysis
      timeline: string;          // Implementation timeline
    };
  };
  testimonials: {
    // Detailed case studies with HTML formatting
    caseSituation1: string;   // First case study's current situation
    caseSolution1: string;    // First case study's solution implementation
    caseValue1: string;       // First case study's results and impact
    caseSituation2: string;   // Second case study's current situation
    caseSolution2: string;    // Second case study's solution implementation
    caseValue2: string;       // Second case study's results and impact
  };
  sessionId: string; // Unique identifier for the solution generation session
}

// Comprehensive state representing the entire discovery and solution process
export interface DiscoveryState {
  currentState: {
    barriers: string[];        // Specific barriers identified
    financialImpact: string;   // Financial implications of current barriers
    targetDate: string;        // Date by which barriers need to be addressed
    emotionalImpact: string;   // Emotional toll of current challenges
  };
  futureState: {
    desiredOutcomes: string[]; // Specific outcomes the prospect wants to achieve
    financialImpact: string;   // Anticipated financial improvement
    emotionalRelief: string;   // Expected emotional benefits
  };
  stage: number;               // Current stage in the discovery process
  prospectInfo: ProspectInfo;  // Detailed prospect information
  sessionName: string;         // Name or identifier for the discovery session
  sessionId?: string;          // Unique identifier for the session
  aiSummary: {
    currentState: {
      barrierThemes: string[];     // AI-generated barrier themes
      emotionalThemes: string[];   // AI-identified emotional themes
      urgencyStatement: string;    // AI's assessment of urgency
    };
    futureState: {
      outcomeThemes: string[];         // AI-generated outcome themes
      emotionalImpactThemes: string[]; // AI-identified future emotional themes
      financialImpactStatement: string;// AI's assessment of financial potential
    };
  };
  solution?: string;           // User-selected solution type
  solutionResponse?: SolutionResponse; // Detailed solution generated by AI
  showError?: boolean;         // Flag to indicate if an error should be displayed
}

// Represents a persistent discovery session with additional metadata
export interface DiscoverySession extends Omit<DiscoveryState, 'stage'> {
  id: string;                  // Unique identifier for the session
  status: 'draft' | 'in_progress' | 'completed'; // Current status of the session
  createdAt: string;           // Timestamp of session creation
  updatedAt: string;           // Timestamp of last update
  userId: string;              // User who created the session
  companyId: string;           // Company associated with the session
}